### ISSUE TITLE
is not detected after flashing

### ISSUE THREAD

**Issue by indevor** [romasku/tuya-zigbee-switch#1]
Hi and thanks for this firmware. This is great news! However, I have encountered a problem.
After reflashing the device is not detected. The “reset” button doesn't help.
All instructions were followed as described.
At 100% the light was turned off automatically - it was not clear whether the device has already been flashed and can be removed or the process is not complete. The indicator was at 100% the boot animation was saved. After completion I removed the device “forced”. I tried to find it, also pressed reset from 5 to 20 sec. the device does not appear.
Tomorrow I will try to physically disconnect it from the power supply.

**Comment by romasku** [comment]
I'm sorry to hear that. It sounds like you'll need a hardware programmer to restore your device, I'll post an instruction today.

**Comment by klu16** [comment]
Same here. Device flashed via OTA as per instructions. Update looks successful. Afterwards the device does not even react to the physical press on the wall switch and seems to be bricked. I tried turning off and on the fuse for around 15 seconds (so cutting out the power to the switch), but it did not help either.
If you have any ideas how to troubleshoot it further, I am open to suggestions.

**Comment by romasku** [comment]
I've added [an instruction on how to flash using programmer](https://github.com/romasku/tuya-zigbee-switch/blob/main/docs/ts0012_flashing_via_wire.md). I'm looking into OTA update issue itself now.

**Comment by indevor** [comment]
I re-flashed it according to your instructions and it worked.
but I see one problem and one wish.
1. As I think the problem. Very frequent network polling/sending to the network, 1 time per second and / or more often. If there will be 3-5-7 devices I think the “air” will be overloaded, I may be wrong.

![1](https://github.com/user-attachments/assets/f1c22824-68a6-42e4-82ea-578d08f2acca)


3. Request. Add “Do not disturb” in case of power failure, if possible.
![3](https://github.com/user-attachments/assets/ea06fedd-f65c-4bbc-8bd9-906ea0f09c6b)

With a short test - it's great! The speed is really excellent, as far as I could quickly assess the bug with sticking of the second key is no more.

![2](https://github.com/user-attachments/assets/8a81376b-2435-4bf9-b90f-b1d6b327a355)


Thanks again! If additional testing is needed I'm ready)

**Comment by romasku** [comment]
Regarding the OTA issue:
It seems that the build with the new SDK fails to boot after the update. I couldn’t pinpoint the exact issue, but it works fine with the older SDK (already in the main branch). I’ve tested it several times, and it’s working correctly now.

For bricked devices, unfortunately, the only solution is to flash them using a programmer.

------

> Very frequent network polling/sending to the network

This should be configurable in the reporting tab. Additionally, I noticed that you didn’t add a custom converter, `ts0012_custom.js` (as referenced in [[this guide](https://github.com/romasku/tuya-zigbee-switch/blob/main/docs/ota_flash.md)](https://github.com/romasku/tuya-zigbee-switch/blob/main/docs/ota_flash.md)). As a result, Zigbee2MQTT is using the default settings, which might be causing the issue. So I suggest you to add the custom converter.

![Screenshot From 2024-12-25 19-26-52](https://github.com/user-attachments/assets/3e7df072-3299-4dd2-bc70-43b528a9579f)

If the converter is working, device settings should look like this:

![Screenshot From 2024-12-25 19-26-34](https://github.com/user-attachments/assets/40d7b2a4-4975-4492-9122-109faae7384e)


------

> Add “Do not disturb” in case of power failure, if possible.

Sure, I'll add it later.

**Comment by klu16** [comment]
I flashed it with UART programmer and it works (at least the switch powers the light up).
But it looks the same as in indevor's post:
![Screenshot_2024-12-25-19-35-35-643_io homeassistant companion android](https://github.com/user-attachments/assets/3e95d0db-5ee3-4bf2-bdc2-c96b172a9829)
I have custom converter added as per instructions:
![Screenshot_2024-12-25-19-41-06-843_io homeassistant companion android](https://github.com/user-attachments/assets/6e9f95b1-ed78-4bc5-99c2-18fb51c67fd4)
Should I do something more?

The other issue I faced is that I have bell switches as physical switches on the wall (the switch gets back to the original position after pressing) like in a doorbell.
With this custom firmware, I need to press and hold so the light shines. When I release the button, it turns off. The original firmware does not behave like this.

I think it's "Switch type" as "Toggle", but I can't choose it, it's not visible as you can see on the screenshot.

**Comment by romasku** [comment]
Hi, this doesn't look like a converter, let me check, it should be JS file.

**Comment by romasku** [comment]
Hi, sorry, there was not a "raw" link, but an ordinary GitHub link. I've updated the docs. Correct link:

https://github.com/romasku/tuya-zigbee-switch/raw/refs/heads/main/zigbee2mqtt/converters/ts0012_custom.js

The switch type you need is "Momentary", firmware supports it.

**Comment by klu16** [comment]
Thanks a lot! After swapping the custom.js file, everything works as expected! 😊 (haven't tested the simultaneous press with 2 buttons yet, though).
Just to confirm, is the OTA issue fixed now? I don't like to mess with my walls again, not to mention soldering is not my thing at all 😉

**Comment by romasku** [comment]
Glad to hear it’s fixed for you!

The OTA issue has been resolved — I was able to reproduce the problem, and after updating the code, it works for me. However, I still recommend flashing the devices one at a time and being prepared, as I can’t guarantee everything will go perfectly. This is my first attempt at firmware development.

Thank you both for testing it and helping me improve it. Hopefully, it will be a smoother experience for others now.

**Comment by romasku** [comment]
If the OTA works for you, please let me know here so I can close the issue.

**Comment by indevor** [comment]
Thanks for the promptness of the problem solving and clarification about custom.js I replaced, now the interface is like yours.
I will re-flash the second relay during the evening and close the problem if all is well.

**Comment by klu16** [comment]
> If the OTA works for you, please let me know here so I can close the issue.

I will test it first thing tomorrow morning, as now is the night time for me and I don't want to have a blackout in my home if anything goes wrong (like the first time) 🤣 The wifey would be fu**ing pissed off lol.

**Comment by indevor** [comment]
Flashed via OTA, success. (re-download index.json if you have tried to install it before now)
Although never got to the moment of 100% installation and re-installation/uninstallation. I needed to force reboot z2m in addition to uninstalling the device, so access to the “reset” button of the device is highly recommended.
wait for 100% and end of animation (twist button) -> delete device (force) -> reboot z2m -> press reset >2 sec -> allow connection. My setup.

**Comment by klu16** [comment]
Hey @romasku! Before I proceed with the upgrade, is there a way to trigger pairing mode from the physical buttons (I mean on the wall, not the reset button on TS0012). On the stock firmware, you have to use left button to turn on and off the light 5 times (10 presses in total). I checked the device that I have already upgraded with your firmware, but this method doesn't seem to work... Do I need a physical access to the TS0012 every time I want to pair it (with a reset button on it)?

**Comment by romasku** [comment]
I haven't implementated such feature yet, so yes, you need physical access to device to reset it now.
If device is kicked from network it tries to reconnect, but eventually stops trying. This can be restarted by cutting power (e. g. via circuit breaker).
I personally was able to flash and reconnect device without opening wall, but it wasn't straightforward, unfortunately.

**Comment by klu16** [comment]
Got it! I didn't think of using the circuit breaker to reset, thx. But I think such feature would be great, though :) Thanks again.

**Comment by klu16** [comment]
A little update from me that the OTA update was finished successfully (just had to upload the files again, I don't know why... some error appeared regarding the custom converter). After that I force removed the device and restarted Z2M. It was discovered automatically, didn't need to use "reset" button.
PS. I confirm that simultaneously pressing both physical switches turns both lights on at the same time. Awesome! And reaction time is a LOT better as well.
👌😄
I will advertise your firmware in the biggest Polish Home Assistant group on Facebook. I know a lot of people were complaining about issues that are now fixed 🤘
