### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by indevor** [romasku/tuya-zigbee-switch#2]
I keep testing and it works great.
If you can, please implement the functions:
1. Switch mode - "state" - relay operates and behaves depending on the state of the switch (physical). If it is in the “off” position, but has been turned on by the GUI, moving the switch (physical) to the “on” position will NOT turn off the lights.
2. Power-on behavior - Controls the behavior when the device turns on after a power loss (on \ off \ previous).

**Comment by klu16** [comment]
I just noticed that too, state is not reported. So when you turn on the light with the wall switch, the state of the switch remains off in HA. And vice versa, when you turn on the light in HA app and turn it off on the wall, the state remains "on" in the app.

**Comment by indevor** [comment]
> I just noticed that too, state is not reported. So when you turn on the light with the wall switch, the state of the switch remains off in HA. And vice versa, when you turn on the light in HA app and turn it off on the wall, the state remains "on" in the app.

Yeah, I'm seeing something similar. I haven't figured out how to get the verifiable state of the problem yet. Because I checked it after reading your post, I clicked with the switch, the state changed then it did not.

**Comment by romasku** [comment]
> I just noticed that too, state is not reported. So when you turn on the light with the wall switch, the state of the switch remains off in HA. And vice versa, when you turn on the light in HA app and turn it off on the wall, the state remains "on" in the app.

This is due to "reporting" not configured in HA. You can try to reconfigure the device in HA
![Screenshot From 2024-12-27 01-30-06](https://github.com/user-attachments/assets/81ce7e09-9e76-4d44-ba39-47f2661489e6)
Or manually verify that reporting tab is set to something like this:
![Screenshot From 2024-12-27 01-30-30](https://github.com/user-attachments/assets/a1763df9-b925-4f4c-8082-8c04353ed054)
if you see "TABLE_FULL" errors, then you have to reset the device. I'm working on the new version to add support for resetting by clicking buttons 10 times.

The problem with reporting happens because z2m thinks it is just an old device after OTA and there is no need to configure reporting. Also, the device itself reads old reporting settings stored in Flash by stock firmware, and it probably causes TABLE_FULL errors. I have an idea of how to patch firmware to avoid this problem, but it may require re-joining the device.

**Comment by romasku** [comment]
> Switch mode - "state" - relay operates and behaves depending on the state of the switch (physical). If it is in the “off” position but has been turned on by the GUI, moving the switch (physical) to the “on” position will NOT turn off the lights.

It's actually already supported by firmware, I just need to expose it in the converter in z2m. It is called "Action" according to Zigbee spec:
![Screenshot From 2024-12-27 01-40-47](https://github.com/user-attachments/assets/a8f4a08a-1141-4db3-a537-964575e80d0e)

I'll try to do it tomorrow.

> Power-on behavior - Controls the behavior when the device turns on after a power loss (on \ off \ previous).

Totally makes sense, will do that.

**Comment by klu16** [comment]
Indeed...

![Screenshot_2024-12-27-09-20-29-861_io homeassistant companion android](https://github.com/user-attachments/assets/183dc2a1-a81e-4cec-a6ff-d2636ea307cb)

**Comment by romasku** [comment]
Hello, I've pushed a new version that includes the following updates:  
- A reset feature that activates by pressing any button 5 times in a row.  
- Improved support for SwitchActions.  

To use it, please re-download the `index.json` and `ts0012_custom.js` files, then check for OTA updates and update the device. I've thoroughly tested this update during development, so it should work as expected. However, I recommend proceeding with caution: update the devices one by one, starting with the one you can access most easily.

After completing the OTA update, select the appropriate action to achieve the behavior described in (1):  
![Screenshot From 2024-12-27 22-31-26](https://github.com/user-attachments/assets/8232e98e-07e0-41b7-bf28-c2c41d0072fb)  
- **ON_OFF** and **OFF_ON** determine which position of the physical switch corresponds to "ON."  
- **Toggle** retains the current behavior (any physical press toggles the state).  



To resolve issues with the state not being reported:  
1. Reset the device by pressing the button 5 times quickly.  
2. Force-remove the device from z2m and rejoin it.  
3. Check the reporting tab. If it remains empty, press **Reconfigure**.

**Comment by romasku** [comment]
> Failed to check if update available ...

Sounds like a bad Zigbee connection, please retry

**Comment by indevor** [comment]
Great!
**reset** function (5 times) works well
**on_off** function works as expected

P.S only problem with reports
![zigbee1](https://github.com/user-attachments/assets/684ad4ae-3bae-40cc-a9ed-91291bdaed03)

reconfig:

`error 2024-12-28 01:15:06z2m: Failed to configure '0xa4c138689e020fa2', attempt 2 (Error: Bind 0xa4c138689e020fa2/3 genOnOff from '0x00124b0024c1f04d/1' failed (Status 'TABLE_FULL') at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:566:23) at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:160:13) at /app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:546:17 at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:206:21) at Configure.configure (/app/lib/extension/configure.ts:130:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:57:21) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:211:17))`

Interviewing:
`2024-12-28 01:17:02z2m: Interviewing '0xa4c138689e020fa2'
info 2024-12-28 01:17:02zh:controller:device: Device '0xa4c138689e020fa2' is only compliant to revision '21' of the ZigBee specification (current revision: 23).
info 2024-12-28 01:17:03z2m: Successfully interviewed '0xa4c138689e020fa2'`

**Comment by klu16** [comment]
For me everything works as expected ☺️
Now, the state reporting is OK, so when I turn on/off the light via switch on the wall, it turns on/off the switch in the app. Awesome! 
I don't know why, but reset/pairing function is 8 quick presses for me 😅
I noticed that I have one error while interviewing (but still, the device behaves as expected, though).
I caught a screenshot, hope it helps:
![Screenshot_2024-12-28-12-31-30-275_io homeassistant companion android](https://github.com/user-attachments/assets/1ceb9eb2-6b08-433b-9239-e0e99830a3f7)

PS. I updated 2 of them already and in both cases I did not even have to re-pair the devices. They just re-joined by themselves after the update. 

Thanks a lot! 😊

**Comment by romasku** [comment]
Hi again,  

I've released a new version with the following updates:  
- Implemented power-on behavior selection.  
- Fixed the "TABLE_FULL" error.  
- Added support for actions ("release," "press," and "long press"). This feature is only useful for momentary (doorbell-like) buttons, allowing automation activation on a long press. For example, I plan to configure it to turn all lights on or off with a long press.  

To update, re-download `index.json` and `ts0012_custom.js`, update via OTA, and re-interview and reconfigure the device. This is needed to make actions work, as z2m needs to rescan the device capabilities. Without re-interview, you'll see errors like "Device XXX has no input cluster genMultistateInput".

**Comment by indevor** [comment]
I am facing the following problem, maybe I am setting something wrong or I don't understand the principle.

There is a script that is assigned to a button in the GUI - click-  2 lights on, clicked again off.
![zigb1](https://github.com/user-attachments/assets/22f71950-9c7f-48b9-9b8d-e0c256e0a307)

After the firmware was updated (not the latest release), when you click on this button, the light turns on 2 channels work properly, but after 2-3 seconds it turns itself off. But if you go into z2m the switches are on _(The switches are on for a while, then they become off if you restart and refresh the page several times (maybe it's the reports)_.).

The same happens if the switches in z2m are turned on - the light turns itself off after 2-3 seconds

_the physical switch is always in the off position._

**Comment by indevor** [comment]
as far as I understand the “off” event is generated by the relay all the time and not when the switch is physically turned off, which causes the light to turn off, although in z2m it stays on 
_is generated all the time in the off (physical) position of the switch, not during the on-off transition._

I don't think this is the right approach, although it might be more reliable. it would probably be better to generate state not all the time, but only during the transition through on/off -- off/on. otherwise I can't figure out how to make automations and buttons =)

**Comment by romasku** [comment]
Hmm, It should not happen, I'll check it later. I do not use ONOFF, so maybe I missed something during development. Can you please send a screenshot of the device configuration ("Exposes" tab, the second one)? Also if buttons are physically "ON", and you turn them off via HA do they turn on after some delay?

**Comment by indevor** [comment]
It's super weird what's going on. now the light turns on and off after 2 seconds when physically turned on.
now it turns on after 5 times in a circular cycle.....
I don't know what to say or what to do.)

**Comment by indevor** [comment]
Now the light is behaving as it should. could this be some kind of command buffer?
does a tab with z2m open on another device with switches generate the off event or does it only work when interacting (not in the background)?

![zigb1](https://github.com/user-attachments/assets/95f3fb9c-c02c-404a-ad06-6b2e33393dcc)

**Comment by romasku** [comment]
It may be weak Zigbee network. If device reseives request but acknowledgement are not received, it will retry send after some delay, and toggle device one more time. Issue becomes worse when you send a lot of commands.

**Comment by romasku** [comment]
72lqi is somewhat bad connection, as far as I know.

**Comment by indevor** [comment]
> It may be weak Zigbee network. If device reseives request but acknowledgement are not received, it will retry send after some delay, and toggle device one more time. Issue becomes worse when you send a lot of commands.

The strange thing is that during that glitch, the GUI buttons worked perfectly with 0 delay, and the light turned off strictly after 2-3 seconds.

**Comment by romasku** [comment]
Gui buttons are oprimistic, they do not wait for response.

**Comment by indevor** [comment]
> Gui buttons are oprimistic, they do not wait for response.

I meant that GUI buttons (or z2m buttons) turned on the light and it turned on without delays and glitches and turned off strictly after 2-3 seconds.

**Comment by indevor** [comment]
Re-flashed the new firmware everything looks fine, do not disturb function works.  the “reports” function doesn't seem to be a problem anymore  Thanks for the work! 

when switching: Switch 1 action
z2m: No converter available for 'set' 'switch_1_action' (undefined)

**Comment by indevor** [comment]
Playing with the reports. Visually I can see the sending of data in z2m - map.

Field Min. report interval - the time after which a new report will be sent, provided that the new value has changed in any direction, by the amount specified in the field “Min. report interval at change”, compared to the previous values. The time is specified in seconds.
![zigbee1](https://github.com/user-attachments/assets/2ca290be-12a4-4483-8fbc-644318207210)


According to the map and my setting (2 sec) reports are sent with this delay. But I have a question. According to the definition they should be sent when something has changed, but what (and why) is being sent if the relay is in static position and the buttons are not pressed?

**Comment by romasku** [comment]
I was able to reproduce additional reports (for some reason they only happen when light is on). I'll post an update when I'll fix it.

**Comment by romasku** [comment]
@indevor I've published a new version, there was a bug: the code didn't store previous values to compare for change. Now it should be fixed.

**Comment by indevor** [comment]
@romasku reports are fixed, I don't see frequent exchanges anymore. Thank you
when when you change the values (on_off, off_on, toggle): **Switch 1 action** or **Switch 2 action** - error
`z2m: No converter available for 'set' 'switch_1_action' (undefined)`

**Comment by romasku** [comment]
Sorry, there was a bug in converter (I named two different properties `switch_1_action`). Please re-download `ts0012_custom.js`.

**Comment by indevor** [comment]
@romasku Works like a clock, thank you)
